name: lost_and_found
description: "A new Flutter project."
publish_to: 'none' # Projet privé, pas de publication sur pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Déclaration des assets (images, logos, etc.)
  assets:
    - assets/images/logo.png
